[package]
name = "forge-codegen-cranelift"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
forge-fir = { path = "../forge-fir" }
cranelift-codegen = { git = "https://github.com/nickik/crainlift", rev = "3adbcfc1d380e7eab19b9c23ba7e989ed3caccaf", default-features = false, features = ["std", "arm64", "riscv64", "sia32"] }
target-lexicon = { git = "https://github.com/nickik/crainlift", rev = "3adbcfc1d380e7eab19b9c23ba7e989ed3caccaf", package = "target-lexicon" }
